---
openapi: "3.0.2"
info:
  title: Test API
  version: 1.0.0

paths:
  /database/name:
    get:
      operationId: getDatabaseName
      responses:
        '200':
          description: "Returned database name."