[[clowder-extension-for-quarkus]]
= Clowder Extension for Quarkus

include::./includes/attributes.adoc[]

:config-file: application.properties
:extension-status: preview

https://github.com/RedHatInsights/clowder[Clowder] is a kubernetes operator designed to make it easy to deploy
applications running on the cloud.redhat.com platform in production, testing and local development environments.

When deploying a Quarkus service on the cloud, the Clowder operator provides a config file that the services need
to use for configuring the datasource, kafka, logging, etc. The clowder config file looks like:

[source,json]
----
{
  "database": {
    "adminPassword": "s3cr3t",
    "adminUsername": "postgres",
    "hostname": "some.host",
    "name": "some-db",
    "password": "secret",
    "port": 15432,
    "sslMode": "require",
    "username": "aUser"
  },
  "endpoints": [
    {
      "app": "notifications",
      "hostname": "n-api.svc",
      "name": "api",
      "port": 8000
    },
    {
      "app": "notifications",
      "hostname": "n-gw.svc",
      "name": "gw",
      "port": 8000
    }
  ],
  "kafka": {
    "brokers": [
      {
        "hostname": "ephemeral-host.svc",
        "port": 29092
      }
    ],
    "topics": [
      {
        "name": "platform-tmp-12345",
        "requestedName": "platform.notifications.ingress"
      },
      {
        "name": "platform-tmp-666",
        "requestedName": "platform.notifications.alerts"
      }
    ]
  },
  "logging": {
    "cloudwatch": {
      "accessKeyId": "my-key-id",
      "logGroup": "my-log-group",
      "region": "eu-central-1",
      "secretAccessKey": "very-secret"
    },
    "type": "cloudwatch"
  },
  "metricsPath": "/metrics",
  "metricsPort": 9000,
  "privatePort": 10000,
  "publicPort": 8000,
  "webPort": 8000
}
----

This extension eases the integration with the Clowder configuration by loading the file and autoconfiguring some extensions like Quarkus datasource and Quarkus messaging.

Before getting started, make sure you're using the right Quarkus Clowder version that is compatible with the Quarkus version you're using in your project. See the following table to see the compatibility among versions:

[%header,format=csv]
|===
Quarkus Clowder Version,Quarkus Version
0.0.0,Quarkus 3.7.0+
|===

[[usage-clowder]]
== Using the Clowder Extension

To complete this guide, you need:

* roughly 10 minutes
* JDK 17+ installed with `JAVA_HOME` configured appropriately
* Apache Maven {maven-version}

=== Create a Quarkus application with the Clowder extension

In this example, we'll create a Quarkus application with the Quarkus Clowder extension by running the following command:

[source,bash,subs=attributes+]
----
mvn io.quarkus.platform:quarkus-maven-plugin:{quarkus-version}:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=clowder-quickstart \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello" \
    -Dextensions="resteasy-reactive,clowder"
cd clowder-quickstart
----

If you already have your Quarkus project configured, you can add the `clowder` extension to your project by running the following command in your project base directory:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="clowder"
----

This command will add the following dependency to your `pom.xml` file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.clowder</groupId>
    <artifactId>quarkus-clowder</artifactId>
    <version>{quarkus-clowder-version}</version>
</dependency>
----

Next, you need to configure the location where the clowder config file will be located when running the service. The default location is `/cdapp/cdappconfig.json` but it can be configured by using the `quarkus.clowder.config-path` property.

Let's add a simple clowder config file named `cdappconfig.json` at `src/main/resources` with the following content:

[source,json]
----
{
  "database": {
    "adminPassword": "s3cr3t",
    "adminUsername": "postgres",
    "hostname": "some.host",
    "name": "some-db",
    "password": "secret",
    "port": 15432,
    "sslMode": "require",
    "username": "aUser"
  },
  "webPort": 8000
}
----

And configure our application to use it:

[source,properties]
----
quarkus.clowder.config-path=src/main/resources/cdappconfig.json
----

Automatically, the extension will expose all the properties within the clowder config file using the prefix `clowder.`. So, let's add a service that displays the database name as follows:

[source,java]
----
@Path("")
public class Endpoint {

    @ConfigProperty(name = "clowder.database.name")
    String databaseName;

    @GET
    @Path("/database/name")
    public String getDatabaseName() {
        return databaseName;
    }
}
----

Next, let's run our service in Quarkus DEV mode:

[source,bash]
----
./mvnw quarkus:dev
----

And finally, we'll see the expected value by hitting the `/database/name` endpoint:

[source,bash]
----
curl localhost:8000/database/name
some-db
----

**Note**: The Quarkus service will be listening on port 8000 because the Clowder file contains `webPort: 8000`.

== Datasource Configuration

The Quarkus Clowder configuration will automatically configure the Hibernate ORM or Hibernate Reactive extensions.
All you need is to provide the datasource configuration in the clowder config file as follows:

[source,json]
----
{
  "database": {
    "adminPassword": "s3cr3t",
    "adminUsername": "postgres",
    "hostname": "some.host",
    "name": "some-db",
    "password": "secret",
    "port": 15432,
    "sslMode": "require",
    "username": "aUser"
  },
  ...
}
----

Plus, configure the `db-kind` to use (this is a mandatory property for Quarkus):

[source,properties]
----
quarkus.datasource.db-kind=postgresql
----

Then, the Quarkus Clowder extension will detect which Hibernate ORM or Hibernate Reactive is in use and configure the JDBC connection accordingly.

**Note**: In case of you're using other `db-kind` than `postgresl` or you don't have any Quarkus Hibernate extension, then the Quarkus Clowder extension will do nothing since Clowder only supports postgresql.

== Kafka Configuration

The Quarkus Clowder configuration will automatically configure the Kafka bootstrap servers, plus it will provide some properties to expose the topics from the Clowder config file.
All you need is to provide the kafka configuration in the clowder config file as follows:

[source,json]
----
{
  "kafka": {
    "brokers": [
      {
        "hostname": "localhost",
        "port": 29092
      }
    ],
    "topics": [
      {
        "name": "platform-tmp-12345",
        "requestedName": "platform.notifications.ingress"
      }
    ]
  },
  ...
}
----

With the above configuration, the Quarkus Clowder extension will autoconfigure the `kafka.bootstrap.servers` property and, additionally, it will expose the configured topics as follows:

[source,properties]
----
mp.messaging.incoming.prices.connector=smallrye-kafka
mp.messaging.incoming.prices.topic=${clowder.kafka.topics."platform.notifications.ingress".name}
----

The property `clowder.kafka.topics."platform.notifications.ingress".name` will have the value `platform-tmp-12345`.

== Endpoints Configuration

The Clowder configuration includes the endpoints configuration that the service needs. For example:

[source,json]
----
{
  ...
  "endpoints": [
    {
      "name": "api",
      "app": "notifications",
      "hostname": "service.host1",
      "port": 8081
    },
    {
      "name": "api",
      "app": "another",
      "hostname": "service.host2",
      "port": 8081
    }
  ],
  ...
}
----

To use the above endpoints in Quarkus, you generally need either the Quarkus REST Client Reactive or the Quarkus REST Client Legacy extensions. Then, when any of these extensions are present, the Quarkus Clowder extension will autoconfigure these REST Clients automatically by using the URL provided from the Clowder configuration file.
For example, let's add the following REST Client interface:

[source,java]
----
package io.quarkiverse.clowder.tests.endpoints;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

@RegisterRestClient
@Path("/database/name")
public interface AnotherApi {

    @GET
    String getDatabaseName();
}
----

In the above example, we want to use the Clowder endpoint configuration with app "another" and name "api", so we would need to add the following property:

[source,properties]
----
quarkus.clowder.endpoints."another.api".client=io.quarkiverse.clowder.tests.endpoints.AnotherApi
----

And the Quarkus Clowder extension will autoconfigure the REST Client URL and the certification configuration if needed.

Another option to generate the REST Client is via https://docs.quarkiverse.io/quarkus-openapi-generator/dev/index.html[the Quarkus OpenAPI generator] extension:

[source,xml]
----
<dependency>
  <groupId>io.quarkiverse.openapi.generator</groupId>
  <artifactId>quarkus-openapi-generator</artifactId>
  <version>...</version>
</dependency>
----

When using this method, you need to provide the openapi definition at the `src/main/openapi` folder. For example, let's add the `notifications_api.yaml` file with the following content:

[source,yaml]
----
openapi: "3.0.2"
info:
  title: Test API
  version: 1.0.0

paths:
  /database/name:
    get:
      operationId: getDatabaseName
      responses:
        '200':
          description: "Returned database name."
----

When building the service, the REST Client interface will be automatically generated and by default it will look like:

[source,java]
----
/**
  * Test API
  * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)</p>
  */
@Path("/database/name")
@RegisterRestClient( configKey="notifications_api_yaml")
@GeneratedClass(value="notifications_api.yaml", tag = "Default")
@ApplicationScoped
public interface DefaultApi {

    @GET
    @GeneratedMethod ("getDatabaseName")
    public jakarta.ws.rs.core.Response getDatabaseName(
    );

}
----

Finally, if the openapi definition file matches the following convention `<clowder endpoint app>_<clowder endpoint name>.yaml`, the Quarkus Clowder extension will autoconfigure everything by you, so you don't need to add any configuration at all.

Note that both methods are perfectly compatible with each other at the same time.

== Metrics Configuration

The Quarkus Clowder configuration will automatically validate and configure the Quarkus Micrometer Prometheus extension.
All you need is to provide the metrics configuration in the clowder config file as follows:

[source,json]
----
{
  ...
  "metricsPath": "/metrics",
  "metricsPort": 9000,
  ...
}
----

A strong requirement to properly configure the Clowder metrics is to enable the HTTP management in port with the right root path:

[source,properties]
----
quarkus.management.enabled=true
quarkus.management.root-path=/
----

These properties are build-time, so we can't overwrite/autopopulate them at runtime. The Quarkus Clowder extension will validate that the above properties are set as expected and will throw an exception at runtime.

Finally, the metrics path will be listening on:

[source,bash]
----
curl localhost:9000/metrics
----

== Resources Manifests Generation Configuration

The Quarkus Clowder configuration will generate the ClowdApp manifests to be installed on an OpenShift cluster.
By default, the Clowder manifests will be generated at the output folder `deploy/clowdapp.yaml` at build time.

This file will contain a OpenShift template resource with parameters and all the Clowd resources, for example:

[source,yaml]
----
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: quarkus-clowder-integration-tests-resources
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      labels:
        label-a: label-value-a
      name: quarkus-clowder-integration-tests-resources
    spec:
      deployments:
        - name: service
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
          replicas: 1
          webServices:
            public:
              enabled: true
      envName: ${ENV_NAME}
parameters:
  - name: ENV_NAME
    value: test-environment
  - name: IMAGE
    value: quay.io/user/my-image
  - name: IMAGE_TAG
    value: latest

----

To generate the above manifests, it's mandatory to set the pod image. So, either configure any of the Quarkus Container Image extensions to build one, or provide a container image to use via properties:

[source,properties]
----
quarkus.clowder.resources.image=quay.io/user/my-image:latest
----

There are many other options to tweak the generated resources, for example:

[source,properties]
----
quarkus.clowder.resources.env-name=test-environment
quarkus.clowder.resources.labels.label-a=label-value-a
----

To see all the options, go to the xref:#configuration-reference[Configuration Reference].

Another option is to provide an input Template resource that will be used to bootstrap the generated one. For doing this, you need to add a `clowdapp.yaml` at the `src/main/resources` folder.

[[configuration-reference]]
== Configuration Reference

include::includes/quarkus-clowder.adoc[]